# -*- coding: utf-8 -*-
"""Univariate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKMMKOb8_aA_F-AyxpZpOcEqg8qUrgNa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

a=pd. read_csv('/content/Company_data.csv')
a.head()

a.tail()

a.isnull().sum()

"""Here the company dataset has no nul values"""

a.describe()

a.shape

b=a.corr()
sns.heatmap(b,annot=True)

"""Here TV has the highest positive correlation i.e 0.9 so it is taken as x value"""

y=a.iloc[:,-1]
print(y)

X=a.iloc[:,:1]
print(X)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=0)

X_train.shape,X_test.shape

X_train=X_train.values.reshape(-1,1)
Y_train=Y_train.values.reshape(-1,1)

X_train.shape,Y_train.shape



from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
Y_pred=reg.predict(X_train)
                   
print(f'MAE={mean_absolute_error(Y_train,Y_pred)}')
print(f'MSE={mean_squared_error(Y_train,Y_pred)}')
print(f'RMSE={np.sqrt(mean_squared_error(Y_train,Y_pred ))}')
print(f'R_2={r2_score(Y_train,Y_pred)}')

Y_pred=reg.predict(X_test)
                   
print(f'MAE={mean_absolute_error(Y_test,Y_pred)}')
print(f'MSE={mean_squared_error(Y_test,Y_pred)}')
print(f'RMSE={np.sqrt(mean_squared_error(Y_test,Y_pred ))}')
print(f'R_2={r2_score(Y_test,Y_pred)}')

from sklearn.linear_model import Lasso
reg=Lasso(alpha=0.1)
reg.fit(X_train,y_train)

Y_pred=reg.predict(X_train)
                   
print(f'MAE={mean_absolute_error(Y_train,Y_pred)}')
print(f'MSE={mean_squared_error(Y_train,Y_pred)}')
print(f'RMSE={np.sqrt(mean_squared_error(Y_train,Y_pred ))}')
print(f'R_2={r2_score(Y_train,Y_pred)}')

Y_pred1=reg.predict(X_test)
                   
print(f'MAE={mean_absolute_error(Y_test,Y_pred1)}')
print(f'MSE={mean_squared_error(Y_test,Y_pred1)}')
print(f'RMSE={np.sqrt(mean_squared_error(Y_test,Y_pred1 ))}')
print(f'R_2={r2_score(Y_test,Y_pred1)}')

from sklearn.linear_model import Ridge
reg = Ridge(alpha=0.8)
reg.fit(X_train,Y_train)

Y_pred=reg.predict(X_train)
                   
print(f'MAE={mean_absolute_error(Y_train,Y_pred)}')
print(f'MSE={mean_squared_error(Y_train,Y_pred)}')
print(f'RMSE={np.sqrt(mean_squared_error(Y_train,Y_pred ))}')
print(f'R_2={r2_score(Y_train,Y_pred)}')

"""By increasing the alfa value in both lasso & ridge then the values of MAE,MSE,RMSE i.e increase in their values. But the R2 score is decreasing"""

reg.score(X_test,Y_test)

